### ISSUE TITLE
Assorted Bugs/Issues/Suggestions

### ISSUE THREAD

**Issue by FrogBirdd** [Majrusz/MinecraftMods#25]
1. I can't find any information on this, but this mod causes the glint on all enchanted books to be odd colors. After testing it happens without mods that allow for glint coloring (Quark and Charm, specifically). If this is an intended feature, a config for it would be appreciated.
![2021-03-13_14 33 17](https://user-images.githubusercontent.com/47127120/111042004-1d88aa80-8409-11eb-806c-61a63e0c3cbc.png)
2. Magic Protection is compatible with other protection enchantments, and Enchantment Against Humanity is compatible with other damage enchantments, allowing for the creation of slightly overpowered gear.
3. Disabling the Fishing Fanatic enchantment doesn't stop it from appearing on rods in some cases due to its leveling mechanic making it appear when using any rod.
4. The names of many enchantments are somewhat strange, and could use a rename. This isn't a big deal as it can be handled with resource packs. Example renames would be Enchantment Against Humanity to Manslaughter, or Gotta Mine Fast to Acceleration.
5. Not an issue, but I'd like an enchantment that makes arrows fly straighter, perhaps called Bullseye or something similar.

Otherwise I enjoy using this mod, and wish you well on this and all of your projects:)

**Comment by Majrusz** [comment]
1. In the next update there will be new config that will make this modification to not modify Enchantment Book texture and thus solve this problem.
2. 3. This also will be fixed in the next update.
4. I will consider changing these names, but for now I will not change them.
5. I have been thinking about such a enchantment for some time and will certainly add one in the future.

And thanks for your feedback! :)
